# Generated by Django 5.2.5 on 2025-08-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_rescue_app', '0002_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pets/'),
        ),
    ]
