# Generated by Django 5.2.5 on 2025-08-28 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_rescue_app', '0004_pet_created_at_pet_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='updated_at',
        ),
    ]
